export default{
	showMain:({commit})=>{
		commit('showMain')
	},
	showCourse:({commit})=>{
		commit('showCourse')
	},
	showJob:({commit})=>{
		commit('showJob')
	},
	showCtf:({commit})=>{
		commit('showCtf')
	},
	showTarget:({commit})=>{
		commit('showTarget')
	},
	showTool:({commit})=>{
		commit('showTool')
	},
	showPerson:({commit})=>{
		commit('showPerson')
	},
	TShowTools:({commit})=>{
		commit('TShowTools')
	},
	THideTools:({commit})=>{
		commit('THideTools')
	},
	CHidectf:({commit})=>{
		commit('CHidectf')
	},
	CShowctf:({commit})=>{
		commit('CShowctf')
	},
	CHideCourse:({commit})=>{
		commit('CHideCourse')
	},
	CShowCourse:({commit})=>{
		commit('CShowCourse')
	},
	JHideJob:({commit})=>{
		commit('JHideJob')
	},
	JShowJob:({commit})=>{
		commit('JShowJob')
	},
	PHidePerson:({commit})=>{
		commit('PHidePerson')
	},
	PShowPerson:({commit})=>{
		commit('PShowPerson')
	},
	CHideFooter:({commit})=>{
		commit('CHideFooter')
	},
	CShowFooter:({commit})=>{
		commit('CShowFooter')
	}
}