import getters from './getters.js'


const state={
	main:true,
	course:false,
	job:false,
	ctf:false,
	target:false,
	tool:false,
	person:false,
	TShowTools:true,
	CShowCtf:true,
	CShowCourse:true,
	JShowJob:true,
	PShowPerson:true,
	CShowFooter:true
}
const mutations={
	showMain(state){
		state.main=true,
		state.course=false,
		state.job=false,
		state.ctf=false,
		state.target=false,
		state.tool=false,
		state.person=false
	},
	showCourse(state){
		state.main=false,
		state.course=true,
		state.job=false,
		state.ctf=false,
		state.target=false,
		state.tool=false,
		state.person=false
	},
	showJob(state){
		state.main=false,
		state.course=false,
		state.job=true,
		state.ctf=false,
		state.target=false,
		state.tool=false,
		state.person=false
	},
	showCtf(state){
		state.main=false,
		state.course=false,
		state.job=false,
		state.ctf=true,
		state.target=false,
		state.tool=false,
		state.person=false
	},
	showTarget(state){
		state.main=false,
		state.course=false,
		state.job=false,
		state.ctf=false,
		state.target=true,
		state.tool=false,
		state.person=false
	},
	showTool(state){
		state.main=false,
		state.course=false,
		state.job=false,
		state.ctf=false,
		state.target=false,
		state.tool=true,
		state.person=false
	},
	showPerson(state){
		state.main=false,
		state.course=false,
		state.job=false,
		state.ctf=false,
		state.target=false,
		state.tool=false,
		state.person=true
	},
	TShowTools(state){
		state.TShowTools=true
	},
	THideTools(state){
		state.TShowTools=false
	},
	CHidectf(state){
		state.CShowCtf=false
	},
	CShowctf(state){
		state.CShowCtf=true
	},
	CHideCourse(state){
		state.CShowCourse=false
	},
	CShowCourse(state){
		state.CShowCourse=true
	},
	JHideJob(state){
		state.JShowJob=false
	},
	JShowJob(state){
		state.JShowJob=true
	},
	PHidePerson(state){
		state.PShowPerson=false
	},
	PShowPerson(state){
		state.PShowPerson=true
	},
	CHideFooter(state){
		state.CShowFooter=false
	},
	CShowFooter(state){
		state.CShowFooter=true
	}
}

export default{
	state,
	mutations,
	getters
}

